name: Step 1, DHCP Fundamentals

# Triggers when dhcp/README.md is pushed to main.
# Advances from step 1 to step 2.
on:
  workflow_dispatch:
  push:
    paths:
      - "dhcp/README.md"
    branches:
      - main

permissions:
  contents: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_dhcp_fundamentals:
    name: On DHCP Fundamentals
    needs: get_current_step
    if: ${{ !github.event.repository.is_template && needs.get_current_step.outputs.current_step == 1 }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check file contains DORA terms
        uses: skills/action-check-file@v1
        with:
          file: "dhcp/README.md"
          search: "Discover"
      - name: Update to step 2
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 1
          to_step: 2
